In [10]:
import numpy as np

# uno

In [3]:
a = np.array(range(1000))

In [4]:
a.dtype


dtype('int32')

# dos

In [46]:
a = np.arange(2,101,2)
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [86]:
reverse_order = np.sort(a)[::-1]
reverse_order



array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

# tres

# cuatro

In [101]:
x = np.array([1, 4, 2, 7])
y = np.array([1, 3, 2, 9])
print("resta: ", x  - y)

resta:  [ 0  1  0 -2]


In [110]:
from statistics import median

In [112]:
median([0, 1, 0, -2])


0.0

# cinco

In [127]:
a = np.array([[1.33, 4.5], [30, 10.7], [70.2, 0.5]])
a


array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ]])

In [130]:
a = np.append(a, [37.1, -3])
print(a)


[ 1.33  4.5  30.   10.7  70.2   0.5  37.1  -3.  ]


# seis

In [131]:
np.transpose(a)

array([ 1.33,  4.5 , 30.  , 10.7 , 70.2 ,  0.5 , 37.1 , -3.  ])